### ISSUE TITLE
npm version 1.0.2 is not synced with the source code in Github

### ISSUE THREAD

**Issue by Diamondlord** [equalogic/typeorm-relations-graphql#465]
NPM library was last published 4 month ago and has old configuration in package.json that doesn't mention the support of typeorm ^0.3.0
from npm source 
```
  "peerDependencies": {
    "graphql": ">=14.6.0",
    "typeorm": "^0.2.24"
  },
```

P.S. nice library ;)

**Comment by sgarner** [comment]
The `peerDependencies` were updated by renovate bot, even though the library wasn't supporting TypeORM v0.3.x yet.

[Version 2.0.0](https://github.com/equalogic/typeorm-relations-graphql/releases/tag/v2.0.0) has now been released with support for TypeORM v0.3.x.
