### ISSUE TITLE
Request: Implementation that does not use TypeORM connection

### ISSUE THREAD

**Issue by BaharaJr** [equalogic/typeorm-relations-graphql#476]
Library improvement to remove `getConnection` implementation from TypeORM or get something similar to that since version 0.3.0 of TypeORM no longer supports `getConnection` functionality.

**Comment by sgarner** [comment]
[Version 2.0.0](https://github.com/equalogic/typeorm-relations-graphql/releases/tag/v2.0.0) has now been released with support for TypeORM v0.3.x.
